apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/nhatminh06/api-gateway@sha256:e45ec2425732972b013ee47127e6c387203a251845768e7a6801df8e2d6aa29e
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: USER_SVC_URL
              value: "http://user-svc:8081"
            - name: NOTE_SVC_URL
              value: "http://note-svc:8082"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5