apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-svc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/gitops-config.git
    targetRevision: HEAD
    path: apps/user-svc/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: notekeeper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true